image: node:latest # Pulling and installing node into our virtual container

stages:
  # I just want to lint, so I will create a "lint" stage
  - lint

before_script:
  # Install Dev dependency in this docker container (Only devDependencies in package.json)
  - npm install --only=dev

# Lets name our Job eslint, because that's what it's doing.
eslint:
  # tell eslint what stage it is. (This could also be build or test for example)
  stage: lint
  only:
    - pushes
    - merge_requests
  # What scripts do we want to run?
  script:
    # Run ESLint
    - npm run lint
    - echo "hero never dies"